function Get-EventWmiProviderStart {
    <#
    .SYNOPSIS
        Get WMI Provider Start events (EventId 5857).
    .DESCRIPTION
        Get WMI Provider Start events (EventId 5857). from a local or remote host. Events can be filtered by fields.
    .INPUTS
        System.IO.FileInfo
    .OUTPUTS
        System.Management.Automation.PSCustomObject
    #>
    [CmdletBinding(DefaultParameterSetName = 'Local')]
    param (
        # Log name for where the events are stored.
        [Parameter(Mandatory = $false,
                   ValueFromPipelineByPropertyName = $true)]
        [string]
        $LogName = 'Microsoft-Windows-WMI-Activity/Operational',

        # Name of the provider being loaded.
        [Parameter(Mandatory = $false,
                   ValueFromPipelineByPropertyName = $true)]
        [string[]]
        $ProviderName,

        # Full path to the provider that was started.
        [Parameter(Mandatory = $false,
                   ValueFromPipelineByPropertyName = $true)]
        [string[]]
        $ProviderPath,

        # Specifies the path to the event log files that this cmdlet get events from. Enter the paths to the log files in a comma-separated list, or use wildcard characters to create file path patterns. Function supports files with the .evtx file name extension. You can include events from different files and file types in the same command.
        [Parameter(Mandatory=$true,
                   Position=0,
                   ParameterSetName="file",
                   ValueFromPipelineByPropertyName=$true)]
        [Alias("FullName")]
        [ValidateNotNullOrEmpty()]
        [SupportsWildcards()]
        [string[]]
        $Path,


        # Gets events from the event logs on the specified computer. Type the NetBIOS name, an Internet Protocol (IP) address, or the fully qualified domain name of the computer.
        # The default value is the local computer.
        # To get events and event logs from remote computers, the firewall port for the event log service must be configured to allow remote access.
        [Parameter(Mandatory = $true,
                   ValueFromPipelineByPropertyName = $true,
                   ParameterSetName = 'Remote')]
        [string[]]
        $ComputerName,

        # Specifies a user account that has permission to perform this action.
        #
        # Type a user name, such as User01 or Domain01\User01. Or, enter a PSCredential object, such as one generated by the Get-Credential cmdlet. If you type a user name, you will
        # be prompted for a password. If you type only the parameter name, you will be prompted for both a user name and a password.
        [Parameter(Mandatory = $false,
                   ParameterSetName = 'Remote')]
        [Management.Automation.PSCredential]
        [Management.Automation.CredentialAttribute()]
        $Credential,

        # Specifies the maximum number of events that are returned. Enter an integer. The default is to return all the events in the logs or files.
        [Parameter(Mandatory = $false,
                   ValueFromPipelineByPropertyName = $true)]
        [int64]
        $MaxEvents,

        # Stsrttime from where to pull events.
        [Parameter(Mandatory = $false)]
        [datetime]
        $StartTime,

        # Stsrttime from where to pull events.
        [Parameter(Mandatory = $false)]
        [datetime]
        $EndTime,

        # Changes the default logic for matching fields from 'and' to 'or'.
        [Parameter(Mandatory = $false)]
        [switch]
        $ChangeLogic
    )

    begin {}

    process {
        Search-EventLogUsertData -EventId 5857 -Provider "Microsoft-Windows-WMI-Activity" -ReturnRecord -SubElement -ParamHash $MyInvocation.BoundParameters | ForEach-Object {
            [xml]$evtxml = $_.toxml()
            $ProcInfo = [ordered]@{}
            $ProcInfo['EventId'] = $evtxml.Event.System.EventID
            $ProcInfo['Computer'] = $evtxml.Event.System.Computer
            $ProcInfo['EventRecordID'] = $evtxml.Event.System.EventRecordID
            $ProcInfo['TimeCreated'] = [datetime]$evtXml.Event.System.TimeCreated.SystemTime
            $ProcInfo['ProviderName'] = $evtxml.Event.UserData.Operation_StartedOperational.ProviderName
            $ProcInfo['Code'] = $evtxml.Event.UserData.Operation_StartedOperational.Code
            $ProcInfo['HostProcess'] = $evtxml.Event.UserData.Operation_StartedOperational.HostProcess
            $ProcInfo['ProcessId'] = $evtxml.Event.UserData.Operation_StartedOperational.ProcessId
            $ProcInfo['ProviderPath'] = $evtxml.Event.UserData.Operation_StartedOperational.ProviderPath
            $Obj = New-Object psobject -Property $ProcInfo
            $Obj
        }

    }

    end {}
}