function Get-EventPsScriptCommandExec {
    <#
    .Synopsis
    Short description
    .DESCRIPTION
    Long description
    .EXAMPLE
    Example of how to use this cmdlet
    .EXAMPLE
    Another example of how to use this cmdlet
    #>
    [CmdletBinding(DefaultParameterSetName='none')]
    [Alias()]
    [OutputType([PSObject])]
    Param (

        # Log name of where to look for the PowerShell events.
        [Parameter(Mandatory=$false,
                   ValueFromPipelineByPropertyName=$true,
                   Position=0)]
        [string]
        $LogName = 'Microsoft-Windows-PowerShell/Operational',

        # Specifies the path to the event log files that this cmdlet get events from. Enter the paths to the log files in a comma-separated list, or use wildcard characters to create file path patterns. Function supports files with the .evtx file name extension. You can include events from different files and file types in the same command.
        [Parameter(Mandatory=$true,
                    Position=0,
                    ParameterSetName="file",
                    ValueFromPipelineByPropertyName=$true)]
        [Alias("FullName")]
        [ValidateNotNullOrEmpty()]
        [SupportsWildcards()]
        [string[]]
        $Path,


        # Gets events from the event logs on the specified computer. Type the NetBIOS name, an Internet Protocol (IP) address, or the fully qualified domain name of the computer.
        # The default value is the local computer.
        # To get events and event logs from remote computers, the firewall port for the event log service must be configured to allow remote access.
        [Parameter(Mandatory = $true,
                    ValueFromPipelineByPropertyName = $true,
                    ParameterSetName = 'Remote')]
        [string[]]
        $ComputerName,

        # Specifies a user account that has permission to perform this action.
        #
        # Type a user name, such as User01 or Domain01\User01. Or, enter a PSCredential object, such as one generated by the Get-Credential cmdlet. If you type a user name, you will
        # be prompted for a password. If you type only the parameter name, you will be prompted for both a user name and a password.
        [Parameter(Mandatory = $false,
                    ParameterSetName = 'Remote')]
        [Management.Automation.PSCredential]
        [Management.Automation.CredentialAttribute()]
        $Credential,

        # Specifies the maximum number of events that are returned. Enter an integer. The default is to return all the events in the logs or files.
        [Parameter(Mandatory = $false,
                    ValueFromPipelineByPropertyName = $true)]
        [int64]
        $MaxEvents,

        # Stsrttime from where to pull events.
        [Parameter(Mandatory = $false)]
        [datetime]
        $StartTime,

        # Stsrttime from where to pull events.
        [Parameter(Mandatory = $false)]
        [datetime]
        $EndTime,

        # Changes the default logic for matching fields from 'and' to 'or'.
        [Parameter(Mandatory = $false)]
        [switch]
        $ChangeLogic,

        # Changes the query action from inclusion to exclusion when fields are matched.
        [Parameter(Mandatory = $false)]
        [switch]
        $Suppress,

        # ScriptBlock ID GUID that identifies the specific scriptblock on the system. This value is unique per host. 
        [Parameter(Mandatory = $false)]
        [string]
        $ScriptBlockId,

        # RunSpace ID GUID, unique identifier of the PowerShell runspace that executed the script block. 
        [Parameter(Mandatory = $false)]
        [string]
        $RunSpaceId,

        [Parameter(Mandatory = $false)]
        [ValidateSet('All','Start','End')]
        [string]
        $ExecType = 'All'
    )

    Begin {
        $Params = $MyInvocation.BoundParameters
        $Params.Remove("ExecType") | Out-Null
        
    }
    Process {
        [System.Collections.ArrayList]$eventIds = @(4105,4106)
        switch ($ExecType) {
            'Start' { $eventIds.Add(4105) | Out-Null}
            'End' { $eventIds.Add(4106) | Out-Null}
            'All' { }
        }

        Search-EventLogEventData -EventId $eventIds -ParamHash $Params -Provider "Microsoft-Windows-PowerShell" -RecordType "PSScriptExec" 

    }
    End {}
}